export const styles = {
  static: {
    width: 50,
    height: 40,
    'background-color': 'black',
    color: 'yellow',
    'text-align': 'center',
    'vertical-align': 'center',
    'line-height': '40px',
    'border-radius': '25px',
  },

  onHover: {
    width: 50,
    height: 40,
    'background-color': 'yellow',
    color: 'black',
    'text-align': 'center',
    'justify-content': 'center',
    'vertical-align': 'center',
    cursor: 'pointer',
    padding: 'auto',
    'line-height': '40px',
    'border-radius': '25px',
    'box-shadow': '0 3px 5px 2px rgba(255, 105, 135, .3)',
  },
  sideMargins: {
    marginRight: 5,
    marginLeft: 5,
    width: 200,
  },
  inputFields: {
    display: 'flex',
    'background-color': 'rgba(102, 255, 178, .3)',
    margin: 'auto',
    height: 75,
    'border-radius': '5px',
    width: '100%',
    'align-items': 'center',
    'justify-content': 'center',
  },
  hoverInputFields: {
    display: 'flex',
    margin: 'auto',
    'background-color': 'rgba(102, 255, 178, .8)',
    'border-radius': '5px',
    width: '100%',
    height: 75,
    'line-height': 75,
    'justify-content': 'center',
    'align-items': 'center',
  },

  circle: {
    'border-radius': '50%',
    width: '50%',
    height: 130,
    margin: 'auto',
    backgroundColor: 'rgb(221,160,221, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    display: 'flex',
    fontSize: 32,
  },
};
