/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://w4xseixmwvbu3dzt4gs3mclg34.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-f73i7xo7mjac5lbjplkbrydj6u",
    "aws_cognito_identity_pool_id": "us-east-2:81f40dcd-0258-4314-8474-a295c5a6cf72",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_7CEkttIu7",
    "aws_user_pools_web_client_id": "46u3ccrof3tcaijai6h6dpi4br",
    "oauth": {}
};


export default awsmobile;
